org: sourav78
app: new-api-serverless
service: new-api-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  fruitFn:
    handler: fruit.handler
    events:
      - httpApi:
        path: /fruit
        method: get
