service: aws-api-point
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  helloFn:
    handler: sayHello.handler
    events:
      - httpApi:
        path: /hello
        method: GET